-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('client', 'worker', 'admin')),
  profile_pic VARCHAR(255) DEFAULT NULL,
  profile_image VARCHAR(255) DEFAULT NULL,
  paypal_email VARCHAR(255) DEFAULT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  two_factor_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_en VARCHAR(100) NOT NULL,
  name_si VARCHAR(100) NOT NULL,
  icon_class VARCHAR(50) DEFAULT NULL,
  status BOOLEAN DEFAULT TRUE
);

-- 3. Worker Profiles Table
CREATE TABLE IF NOT EXISTS worker_profiles (
  worker_id BIGINT NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  nic_number VARCHAR(20) UNIQUE,
  verification_status TEXT DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected')),
  bio TEXT DEFAULT NULL,
  rating DECIMAL(3,2) DEFAULT 0.00,
  total_reviews INTEGER DEFAULT 0,
  location_lat DECIMAL(10,8) DEFAULT NULL,
  location_lng DECIMAL(11,8) DEFAULT NULL,
  nic_front VARCHAR(255) DEFAULT NULL,
  nic_back VARCHAR(255) DEFAULT NULL,
  is_verified BOOLEAN DEFAULT FALSE
);

-- 4. Jobs / Requests Table
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id),
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  budget DECIMAL(10,2) DEFAULT NULL,
  location_lat DECIMAL(10,8) NOT NULL,
  location_lng DECIMAL(11,8) NOT NULL,
  province VARCHAR(50) DEFAULT NULL,
  district VARCHAR(50) DEFAULT NULL,
  city VARCHAR(100) DEFAULT NULL,
  status TEXT DEFAULT 'open' CHECK (status IN ('pending_payment', 'open', 'in_progress', 'completion_pending_client', 'completed', 'disputed', 'cancelled')),
  assigned_worker_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  accepted_bid_amount DECIMAL(10,2) DEFAULT NULL,
  platform_fee DECIMAL(10,2) DEFAULT NULL,
  refund_amount DECIMAL(10,2) DEFAULT NULL,
  client_completed BOOLEAN DEFAULT FALSE,
  worker_completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Job Images Table
CREATE TABLE IF NOT EXISTS job_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  image_path VARCHAR(255) NOT NULL
);

-- 6. Bids Table
CREATE TABLE IF NOT EXISTS bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  proposal TEXT DEFAULT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Portfolios Table
CREATE TABLE IF NOT EXISTS portfolios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) DEFAULT NULL,
  image_path VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  reviewer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. Payments Table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  client_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  worker_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  paypal_order_id VARCHAR(100) DEFAULT NULL,
  paypal_capture_id VARCHAR(100) DEFAULT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. Gigs Table
CREATE TABLE IF NOT EXISTS gigs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  base_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  description TEXT NOT NULL,
  image_path VARCHAR(255) DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. Contact Messages Table
CREATE TABLE IF NOT EXISTS contact_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_wp_location ON worker_profiles (location_lat, location_lng);
CREATE INDEX IF NOT EXISTS idx_wp_category ON worker_profiles (category_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs (status);
CREATE INDEX IF NOT EXISTS idx_jobs_client_status ON jobs (client_id, status);
CREATE INDEX IF NOT EXISTS idx_jobs_location_text ON jobs (province, district);
CREATE INDEX IF NOT EXISTS idx_ji_job ON job_images (job_id);
CREATE INDEX IF NOT EXISTS idx_bids_job_status ON bids (job_id, status);
CREATE INDEX IF NOT EXISTS idx_bids_worker ON bids (worker_id);
CREATE INDEX IF NOT EXISTS idx_portfolios_worker ON portfolios (worker_id);
CREATE INDEX IF NOT EXISTS idx_reviews_job ON reviews (job_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer ON reviews (reviewer_id);
CREATE INDEX IF NOT EXISTS idx_reviews_worker ON reviews (worker_id);
CREATE INDEX IF NOT EXISTS idx_payments_job_status ON payments (job_id, status);
CREATE INDEX IF NOT EXISTS idx_payments_client ON payments (client_id);
CREATE INDEX IF NOT EXISTS idx_payments_worker ON payments (worker_id);
CREATE INDEX IF NOT EXISTS idx_gigs_worker ON gigs (worker_id);
CREATE INDEX IF NOT EXISTS idx_messages_job ON messages (job_id);
CREATE INDEX IF NOT EXISTS idx_messages_participants ON messages (sender_id, receiver_id);

-- Add Default Categories
INSERT INTO categories (id, name_en, name_si, icon_class, status)
VALUES 
  (1, 'Electrical & Plumbing', 'විදුලි සහ නල පද්ධති', 'icon-electrical', TRUE),
  (2, 'Masonry & Carpentry', 'පෙදරේරු සහ වඩු වැඩ', 'icon-masonry', TRUE),
  (3, 'Cleaning & Painting', 'පිරිසිදු කිරීම් සහ තීන්ත ගෑම', 'icon-cleaning', TRUE)
ON CONFLICT (id) DO UPDATE SET name_en = EXCLUDED.name_en, name_si = EXCLUDED.name_si;

SELECT setval(pg_get_serial_sequence('categories', 'id'), coalesce(max(id), 0) + 1, false) FROM categories;
